version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/generated/prisma
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_TOKEN=${JWT_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15.18-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sipandu
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
